services:
  vue:
    build:
      dockerfile: ./vue-frontend/frontend.Dockerfile
    volumes:
      - ./vue-frontend:/vue-frontend
    ports:
      - 5173:5173
  web:
    env_file: ./web.env
    build: 
      context: ./django-backend
      dockerfile: backend.Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:17.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
